<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MailKit" Version="4.18.1" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.31" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.31" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MiniLMS.Application\MiniLMS.Application.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Identity\" />
	</ItemGroup>

	<!-- ← ضيف ده -->
	<ItemGroup>
		<None Update="Persistence\Seeding\Data\*.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>